name: Release webdav4

on:
  push:
    branches:
    - main
  release:
    types:
      - released

permissions: {}

env:
  FORCE_COLOR: "1"

jobs:
  build-and-publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
            python-version: 3.8

      - run: pip install build
      - run: python -m build

      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
